INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (1, func_key_id_from_name('k'), 'engine', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (1, func_key_id_from_name('l'), 'lights', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (1, func_key_id_from_name('j'), 'lock', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (1, func_key_id_from_name('f'), 'enter', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (1, func_key_id_from_name('g'), 'passenger', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (1, func_key_id_from_name('m'), 'cursor', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (1, func_key_id_from_name('o'), 'drop', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (1, func_key_id_from_name('p'), 'pickup', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (1, func_key_id_from_name('u'), 'use', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (1, func_key_id_from_name('i'), 'inv', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (1, func_key_id_from_name('0'), 'item 0', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (1, func_key_id_from_name('1'), 'item 1', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (1, func_key_id_from_name('2'), 'item 2', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (1, func_key_id_from_name('3'), 'item 3', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (1, func_key_id_from_name('4'), 'item 4', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (1, func_key_id_from_name('5'), 'item 5', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (1, func_key_id_from_name('6'), 'item 6', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (1, func_key_id_from_name('7'), 'item 7', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (1, func_key_id_from_name('8'), 'item 8', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (1, func_key_id_from_name('9'), 'item 9', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (1, func_key_id_from_name('f5'), 'scoreboard', 1);

INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (2, func_key_id_from_name('k'), 'engine', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (2, func_key_id_from_name('l'), 'lights', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (2, func_key_id_from_name('j'), 'lock', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (2, func_key_id_from_name('f'), 'enter', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (2, func_key_id_from_name('g'), 'passenger', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (2, func_key_id_from_name('m'), 'cursor', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (2, func_key_id_from_name('o'), 'drop', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (2, func_key_id_from_name('p'), 'pickup', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (2, func_key_id_from_name('u'), 'use', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (2, func_key_id_from_name('i'), 'inv', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (2, func_key_id_from_name('0'), 'item 0', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (2, func_key_id_from_name('1'), 'item 1', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (2, func_key_id_from_name('2'), 'item 2', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (2, func_key_id_from_name('3'), 'item 3', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (2, func_key_id_from_name('4'), 'item 4', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (2, func_key_id_from_name('5'), 'item 5', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (2, func_key_id_from_name('6'), 'item 6', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (2, func_key_id_from_name('7'), 'item 7', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (2, func_key_id_from_name('8'), 'item 8', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (2, func_key_id_from_name('9'), 'item 9', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (2, func_key_id_from_name('f5'), 'scoreboard', 1);

INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (3, func_key_id_from_name('k'), 'engine', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (3, func_key_id_from_name('l'), 'lights', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (3, func_key_id_from_name('j'), 'lock', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (3, func_key_id_from_name('f'), 'enter', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (3, func_key_id_from_name('g'), 'passenger', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (3, func_key_id_from_name('m'), 'cursor', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (3, func_key_id_from_name('o'), 'drop', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (3, func_key_id_from_name('p'), 'pickup', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (3, func_key_id_from_name('u'), 'use', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (3, func_key_id_from_name('i'), 'inv', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (3, func_key_id_from_name('0'), 'item 0', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (3, func_key_id_from_name('1'), 'item 1', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (3, func_key_id_from_name('2'), 'item 2', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (3, func_key_id_from_name('3'), 'item 3', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (3, func_key_id_from_name('4'), 'item 4', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (3, func_key_id_from_name('5'), 'item 5', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (3, func_key_id_from_name('6'), 'item 6', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (3, func_key_id_from_name('7'), 'item 7', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (3, func_key_id_from_name('8'), 'item 8', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (3, func_key_id_from_name('9'), 'item 9', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (3, func_key_id_from_name('f5'), 'scoreboard', 1);

INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (4, func_key_id_from_name('k'), 'engine', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (4, func_key_id_from_name('l'), 'lights', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (4, func_key_id_from_name('j'), 'lock', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (4, func_key_id_from_name('f'), 'enter', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (4, func_key_id_from_name('g'), 'passenger', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (4, func_key_id_from_name('m'), 'cursor', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (4, func_key_id_from_name('o'), 'drop', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (4, func_key_id_from_name('p'), 'pickup', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (4, func_key_id_from_name('u'), 'use', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (4, func_key_id_from_name('i'), 'inv', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (4, func_key_id_from_name('0'), 'item 0', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (4, func_key_id_from_name('1'), 'item 1', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (4, func_key_id_from_name('2'), 'item 2', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (4, func_key_id_from_name('3'), 'item 3', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (4, func_key_id_from_name('4'), 'item 4', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (4, func_key_id_from_name('5'), 'item 5', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (4, func_key_id_from_name('6'), 'item 6', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (4, func_key_id_from_name('7'), 'item 7', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (4, func_key_id_from_name('8'), 'item 8', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (4, func_key_id_from_name('9'), 'item 9', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (4, func_key_id_from_name('f5'), 'scoreboard', 1);

INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (7, func_key_id_from_name('k'), 'engine', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (7, func_key_id_from_name('b'), 'lights', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (7, func_key_id_from_name('j'), 'lock', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (7, func_key_id_from_name('f'), 'enter', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (7, func_key_id_from_name('m'), 'cursor', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (7, func_key_id_from_name('o'), 'drop', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (7, func_key_id_from_name('p'), 'pickup', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (7, func_key_id_from_name('u'), 'use', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (7, func_key_id_from_name('i'), 'inv', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (7, func_key_id_from_name('0'), 'item 0', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (7, func_key_id_from_name('1'), 'item 1', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (7, func_key_id_from_name('2'), 'item 2', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (7, func_key_id_from_name('3'), 'item 3', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (7, func_key_id_from_name('4'), 'item 4', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (7, func_key_id_from_name('5'), 'item 5', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (7, func_key_id_from_name('6'), 'item 6', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (7, func_key_id_from_name('7'), 'item 7', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (7, func_key_id_from_name('8'), 'item 8', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (7, func_key_id_from_name('9'), 'item 9', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (7, func_key_id_from_name('f5'), 'scoreboard', 1);

INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (10, func_key_id_from_name('k'), 'engine', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (10, func_key_id_from_name('l'), 'lights', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (10, func_key_id_from_name('j'), 'lock', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (10, func_key_id_from_name('f'), 'enter', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (10, func_key_id_from_name('g'), 'passenger', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (10, func_key_id_from_name('m'), 'cursor', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (10, func_key_id_from_name('o'), 'drop', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (10, func_key_id_from_name('p'), 'pickup', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (10, func_key_id_from_name('u'), 'use', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (10, func_key_id_from_name('i'), 'inv', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (10, func_key_id_from_name('0'), 'item 0', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (10, func_key_id_from_name('1'), 'item 1', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (10, func_key_id_from_name('2'), 'item 2', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (10, func_key_id_from_name('3'), 'item 3', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (10, func_key_id_from_name('4'), 'item 4', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (10, func_key_id_from_name('5'), 'item 5', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (10, func_key_id_from_name('6'), 'item 6', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (10, func_key_id_from_name('7'), 'item 7', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (10, func_key_id_from_name('8'), 'item 8', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (10, func_key_id_from_name('9'), 'item 9', 1);
INSERT INTO svr_keybind (svr_keybind_server, svr_keybind_key, svr_keybind_cmd_string, svr_keybind_state) VALUES (10, func_key_id_from_name('f5'), 'scoreboard', 1);